<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$app = (string) file_get_contents($root . '/src/App/SuCasaControlServiciosInmobiliarios.php');
$router = (string) file_get_contents($root . '/src/Http/Api/AuthenticatedActionRouter.php');
$dashboard = (string) file_get_contents($root . '/src/App/Concerns/RendersDashboard.php');
$handler = (string) file_get_contents($root . '/src/App/Concerns/HandlesMaintenanceActions.php');
$runtimeJs = (string) file_get_contents($root . '/public/assets/js/admin-dashboard-runtime.js');
$adminJs = (string) file_get_contents($root . '/public/assets/js/scm-admin.js');
$ticketCompletionJs = (string) file_get_contents($root . '/public/assets/js/ticket-completion-create.js');
$ticketCompletionService = (string) file_get_contents($root . '/src/Modules/TicketCompletion/CompletionService.php');
$ticketCompletionView = (string) file_get_contents($root . '/src/Modules/TicketCompletion/CompletionView.php');
$ticketCompletionHandler = (string) file_get_contents($root . '/src/App/Concerns/HandlesTicketCompletion.php');
$funcionarioBridge = (string) file_get_contents($root . '/public/puente-funcionario.php');
$adminCss = (string) file_get_contents($root . '/public/assets/css/admin/04-dashboard-pending.css');
$publicOrder = (string) file_get_contents($root . '/public/orden-publica.php');
$publicOrderCss = (string) file_get_contents($root . '/public/assets/css/public-order-response.css');
$workflow = (string) file_get_contents($root . '/src/Modules/ServiciosInmobiliarios/Concerns/WorkflowCommandsConcern.php');
$ticketPdf = (string) file_get_contents($root . '/src/Modules/Pending/TicketPdfGenerator.php');
$notificationDelivery = (string) file_get_contents($root . '/src/Modules/ServiciosInmobiliarios/Concerns/NotificationDeliveryConcern.php');
$publicQuote = (string) file_get_contents($root . '/public/cotizacion-mantenimiento.php');
$repairFollowupTemplate = (string) file_get_contents($root . '/docs/whatsapp-seguimiento-reparaciones-template.json');
$quoteSendTemplate = (string) file_get_contents($root . '/docs/whatsapp-cotizacion-mantenimiento-envio-template.json');
$orderOfficialTemplate = (string) file_get_contents($root . '/docs/whatsapp-orden-mantenimiento-funcionario-template.json');
$storedFiles = (string) file_get_contents($root . '/src/Support/StoredFileService.php');
$funcionarioOptions = (string) file_get_contents($root . '/src/Support/FuncionarioOptions.php');
$genericTicketsUi = (string) file_get_contents($root . '/src/Views/GenericTicketsUiView.php');
$historyPresentation = (string) file_get_contents($root . '/src/Modules/ServiciosInmobiliarios/Concerns/HistoryPresentationConcern.php');
$mediaMigrator = (string) file_get_contents($root . '/bin/migrate-media-to-local-storage.php');
$summaryPos = strpos($handler, "\$pdf->heading('Resumen económico');");
$ordersPos = strpos($handler, "\$pdf->heading('Órdenes de mantenimiento');");
$materialsRepeaterPos = strpos($runtimeJs, 'renderCotizacionHiddenRepeaterRows("materiales"');
$materialsSupportRepeaterPos = strpos($runtimeJs, 'renderCotizacionRepeaterRows("materiales_soporte"');
$generatedMaterialsPos = strpos($runtimeJs, 'Materiales generados');
$offersSectionPos = strpos($runtimeJs, 'Ofertas de materiales');
$equipmentRepeaterPos = strpos($runtimeJs, 'renderCotizacionRepeaterRows("equipos"');
$nativeMaterialBudgetPos = strpos($dashboard, 'render_cotizacion_materials_budget_rows($materiales');
$nativeMaterialOffersPos = strpos($dashboard, 'scm-cotizacion-native-material-offers');
$nativeLaborBudgetPos = strpos($dashboard, "render_cotizacion_budget_rows('Mano de obra'");
$perturbDataBoxPos = strpos($runtimeJs, 'Datos cargados desde inmuebles:');
$perturbConditionsPos = strpos($runtimeJs, 'scm-maint-quote-conditions-box');
$perturbTypePos = strpos($runtimeJs, '0. Tipo de valoración');
$actaUnderComplementaryActions = preg_match('/Editar magnitud caso<\/button>\',\s+\'<button type="button" class="scm-case-work-btn" data-scm-open-ticket-acta>Acta de solución y firma<\/button>\'/u', $adminJs) === 1;
$actaStillUnderMainActions = preg_match('/data-scm-open-ticket-response>Responder ticket<\/button>\',\s+\'<button type="button" class="scm-case-work-btn" data-scm-open-ticket-acta>Acta de solución y firma<\/button>\'/u', $adminJs) === 1;

$checks = [
  'app defines approve quote action' => str_contains($app, "AJAX_APPROVE_COTIZACION") && str_contains($app, "scm_aprobar_cotizacion_mantenimiento"),
  'router maps approve quote action' => str_contains($router, "AJAX_APPROVE_COTIZACION") && str_contains($router, "ajax_handler_approve_cotizacion_mantenimiento"),
  'runtime exposes approve quote action' => str_contains($dashboard, "'approve_cotizacion' => self::AJAX_APPROVE_COTIZACION"),
  'app defines native quote order actions' => str_contains($app, "AJAX_COTIZACION_ORDER_CONTEXT") && str_contains($app, "AJAX_COTIZACION_ORDER_SAVE") && str_contains($app, "AJAX_COTIZACION_ORDER_RESPONSE"),
  'router maps native quote order actions' => str_contains($router, "ajax_handler_cotizacion_order_context") && str_contains($router, "ajax_handler_cotizacion_order_save") && str_contains($router, "ajax_handler_cotizacion_order_response"),
  'runtime exposes native quote order actions' => str_contains($dashboard, "'cotizacion_order_context' => self::AJAX_COTIZACION_ORDER_CONTEXT") && str_contains($dashboard, "'cotizacion_order_save' => self::AJAX_COTIZACION_ORDER_SAVE") && str_contains($dashboard, "'cotizacion_order_response' => self::AJAX_COTIZACION_ORDER_RESPONSE"),
  'app defines native maintenance quote form actions' => str_contains($app, 'AJAX_COTIZACION_FORM_CONTEXT') && str_contains($app, 'AJAX_COTIZACION_SAVE') && str_contains($app, 'scm_guardar_cotizacion_mantenimiento'),
  'router maps native maintenance quote form actions' => str_contains($router, 'ajax_handler_cotizacion_mantenimiento_form_context') && str_contains($router, 'ajax_handler_cotizacion_mantenimiento_save'),
  'runtime exposes native maintenance quote form actions' => str_contains($dashboard, "'cotizacion_form_context' => self::AJAX_COTIZACION_FORM_CONTEXT") && str_contains($dashboard, "'cotizacion_save' => self::AJAX_COTIZACION_SAVE"),
  'app defines native quote send action' => str_contains($app, 'AJAX_SEND_COTIZACION_MANTENIMIENTO') && str_contains($app, 'scm_enviar_cotizacion_mantenimiento'),
  'router maps native quote send action' => str_contains($router, 'AJAX_SEND_COTIZACION_MANTENIMIENTO') && str_contains($router, 'ajax_handler_send_cotizacion_mantenimiento'),
  'runtime exposes and opens native quote send action' => str_contains($dashboard, "'send_cotizacion' => self::AJAX_SEND_COTIZACION_MANTENIMIENTO") && str_contains($runtimeJs, 'actionSendCotizacion') && str_contains($runtimeJs, 'openSendCotizacionModal') && str_contains($runtimeJs, '[data-scm-send-cotizacion]'),
  'quote send button only appears for unsent pending editable quotes' => str_contains($dashboard, '$cotizacionPuedeEnviarse') && str_contains($dashboard, '!$enviada') && str_contains($dashboard, 'data-scm-send-cotizacion') && str_contains($dashboard, 'Enviar cotizaci&oacute;n'),
  'backend sends quote through shared email and whatsapp queues with PDF' => str_contains($handler, 'ajax_handler_send_cotizacion_mantenimiento') && str_contains($handler, 'cotizaciones_mantenimiento_envio') && str_contains($handler, 'EmailQueue') && str_contains($handler, 'SmsQueue') && str_contains($handler, 'maintenance_quote_store_pdf_document') && str_contains($handler, "'attachments' => [[") && str_contains($handler, "'type' => 'document'"),
  'quote send marks quote and ticket as waiting response only after enqueue' => str_contains($handler, "'se_envio' => 'Si'") && str_contains($handler, "'estado' => 'Esperando respuesta'") && str_contains($handler, "'fecha_envio' => \$now") && str_contains($handler, "'fue_enviada_cotizacion_mantenimiento' => 'Si'") && str_contains($handler, "'fecha_envio_cotizacion_mantenimiento' => \$now"),
  'quote send whatsapp uses signed public link dynamic suffix' => str_contains($handler, 'signedMaintenanceQuotePublicUrl($cotizacionId)') && str_contains($handler, 'maintenance_quote_whatsapp_url_button_suffix($quoteUrl)') && str_contains($handler, "'button_url_mode' => 'dynamic_suffix'") && str_contains($handler, "'template_name' => 'scm_cotizacion_mantenimiento_envio_v1'"),
  'quote send whatsapp template documents pdf header and response button' => str_contains($quoteSendTemplate, '"format": "DOCUMENT"') && str_contains($quoteSendTemplate, 'Ver y responder') && str_contains($quoteSendTemplate, 'https://sucasainmobiliaria.com.co/{{1}}') && !str_contains($quoteSendTemplate, '%7B%7B1%7D%7D'),
  'quote send whatsapp template includes contract and address variables' => str_contains($quoteSendTemplate, 'Contrato: #{{5}}') && str_contains($quoteSendTemplate, 'Dirección: {{6}}') && str_contains($quoteSendTemplate, '{{7}}') && str_contains($handler, '$contratoRef') && str_contains($handler, '$direccionRef') && str_contains($handler, "maintenance_quote_whatsapp_text(\$contratoRef") && str_contains($handler, "maintenance_quote_whatsapp_text(\$direccionRef"),
  'quote cards render quick approval button' => str_contains($dashboard, 'data-scm-approve-cotizacion') && str_contains($dashboard, 'Marcar como aprobada'),
  'quote cards show state-changing actions only while pending' => str_contains($dashboard, '$cotizacionSinResponder ?') && !str_contains($dashboard, '$cotizacionFinalizada'),
  'quote card approve and delete actions use semantic colors' => str_contains($dashboard, 'scm-cotizacion-approve-action') && str_contains($dashboard, 'scm-cotizacion-delete-action'),
  'quote approve and delete popups use semantic confirm colors' => str_contains($runtimeJs, 'confirmButtonColor: "#16a34a"') && str_contains($runtimeJs, 'confirmButtonColor: "#b91c1c"'),
  'quote panel omits finalized buckets' => !str_contains($dashboard, "'label' => 'Finalizadas'") && !str_contains($dashboard, "'key' => 'finalizadas'") && !str_contains($handler, 'kpi_finalizadas'),
  'quote panel omits sent buckets' => !str_contains($dashboard, "'label' => 'Enviadas'") && !str_contains($dashboard, "'key' => 'enviadas'") && !str_contains($handler, 'kpi_enviadas'),
  'quote contact uses real responsible instead of contractual coordinator default' => str_contains($dashboard, 'cotizacion_responsable_contact') && str_contains($handler, 'cotizacion_responsable_contact') && !str_contains($dashboard, 'Coordinador contractual') && !str_contains($handler, 'Coordinador contractual'),
  'recipient quote view hides internal financial control' => str_contains($dashboard, 'if ($isFuncionario)') && str_contains($dashboard, 'Control financiero') && str_contains($handler, 'if ($isFuncionario)') && str_contains($handler, "heading('Control de saldos')"),
  'native quote damage title uses any affected area slot' => str_contains($dashboard, '$areaTitle = $areas ?') && !str_contains($dashboard, "\$damage['area_afectada_1'] ?? 'Da&ntilde;o evaluado'"),
  'frontend submits exact quote approval action' => str_contains($runtimeJs, 'actionApproveCotizacion') && str_contains($runtimeJs, 'data-scm-approve-cotizacion') && str_contains($runtimeJs, 'fd.append("id_cotizacion", approveCotizacionId)'),
  'backend updates exact quote by id' => str_contains($handler, 'ajax_handler_approve_cotizacion_mantenimiento') && str_contains($handler, "\$this->db->update(\$table, \$update, ['_ID' => \$cotizacionId])"),
  'backend synchronizes linked ticket state' => str_contains($handler, "'estado_cotizacion_mantenimiento' => 'Aprobada'") && str_contains($handler, "'estado_respuesta_cotizacion_mantenimiento' => 'Aprobada'"),
  'quote pdf places economic summary after maintenance orders' => is_int($summaryPos) && is_int($ordersPos) && $summaryPos > $ordersPos,
  'case popup uses the quote selector instead of legacy iframe' => str_contains($adminJs, 'data-scm-view-case-cotizaciones') && !str_contains($adminJs, 'Abrir cotizaci&oacute;n</button>'),
  'case popup only shows quote selector when a quote id or url exists' => str_contains($adminJs, 'if (!isPublicPqr && (cotizacionUrl || cotizacionId))') && !str_contains($adminJs, 'calendarTicketPk || btn.dataset.ticket || cotizacionUrl || cotizacionId'),
  'case cards use quote id found by ticket lookup' => str_contains((string) file_get_contents($root . '/src/Modules/ServiciosInmobiliarios/Concerns/TableRowsConcern.php'), "\$row['id_cotizacion_mantenimiento'] ?? \$row['cot_id']") && str_contains((string) file_get_contents($root . '/src/Modules/Pending/PendingView.php'), "\$ticket['id_cotizacion_mantenimiento'] ?? \$ticket['cot_id']"),
  'quote ajax supports exact ticket lookup from case popup' => str_contains($dashboard, 'fTicketExact') && str_contains($dashboard, "TRIM(COALESCE(c.`id_ticket`, '')) = ?"),
  'case popup loads all quotes for the case instead of using one quote id' => str_contains($adminJs, 'data-scm-view-case-cotizaciones') && str_contains($runtimeJs, 'loadCotizacionCardsByTicket') && str_contains($runtimeJs, 'scmqt_ticket_exact'),
  'case quote selector delegates actions to the selected quote card' => str_contains($runtimeJs, 'scm-case-cotizaciones-modal') && str_contains($runtimeJs, 'triggerCotizacionRootAction') && str_contains($runtimeJs, 'Las acciones se aplican sobre el número de cotización elegido.'),
  'case popup exposes clean create quote for eligible maintenance cases even when quotes exist' => str_contains($adminJs, 'caseCanCreateMaintenanceQuote') && str_contains($adminJs, 'data-scm-create-cotizacion') && str_contains($adminJs, 'data-scm-clear-cotizacion-create-draft') && str_contains($adminJs, 'A&ntilde;adir nueva cotizaci&oacute;n') && str_contains($adminJs, 'prevEncontroDanos') && !str_contains($adminJs, '} else if (!isPublicPqr && caseCanCreateMaintenanceQuote(btn))'),
  'case popup exposes approved quote act button under quote actions' => str_contains($adminJs, 'cotEstadoKey === "aprobada"') && str_contains($adminJs, 'data-scm-cotizacion-acta-button') && str_contains($adminJs, 'Crear acta de cotizaci&oacute;n'),
  'case popup places solution act under complementary actions' => $actaUnderComplementaryActions && !$actaStillUnderMainActions,
  'ticket completion preloads damage and evidence from corrective or preventive review without replacing drafts' => str_contains($ticketCompletionService, 'suggestedItemsForTicket') && str_contains($ticketCompletionService, 'jet_cct_revision_correctiva') && str_contains($ticketCompletionService, 'evaluacion_de_danos') && str_contains($ticketCompletionService, 'jet_cct_revision_preventiva') && str_contains($ticketCompletionService, 'registro_foto_dano') && str_contains($ticketCompletionService, 'actaPhotoDescriptorsFromRefs') && str_contains($ticketCompletionService, 'attachmentPhotoDescriptorsFromIds') && str_contains($ticketCompletionService, '_wp_attached_file') && str_contains($ticketCompletionService, 'wordpressAttachmentPath') && str_contains($ticketCompletionService, 'ctype_digit($ref)') && str_contains($storedFiles, 'storeExistingImagePath') && str_contains($ticketCompletionService, 'StoredFileService::fromRuntime') && str_contains($ticketCompletionService, "'damage_photos'") && str_contains($ticketCompletionHandler, '$allowedDamagePhotos') && str_contains($ticketCompletionHandler, '$allowedSolutionPhotos') && str_contains($ticketCompletionHandler, '$service->context($ticketId, $sourceFlow)') && !str_contains($ticketCompletionService, "'Corresponde a' =>") && str_contains($ticketCompletionView, '$suggestedItems') && str_contains($ticketCompletionView, '$formPayload[\'items\']') && str_contains($ticketCompletionView, '$suggestedItems ?: [[]]') && str_contains($ticketCompletionView, 'Evidencia del daño cargada desde la revisión') && str_contains($ticketCompletionView, 'Fotos de la solución realizada'),
  'wordpress funcionario bridge routes native maintenance actions securely' => str_contains($funcionarioBridge, 'SCM_ACTA_AUTOLOGIN_SECRET') && str_contains($funcionarioBridge, 'loginByEmployeeId($employeeId)') && str_contains($funcionarioBridge, 'scm_bridge_action') && str_contains($funcionarioBridge, 'crear_cotizacion') && str_contains($funcionarioBridge, 'editar_cotizacion') && str_contains($funcionarioBridge, 'enviar_cotizacion') && str_contains($funcionarioBridge, 'crear_orden') && str_contains($funcionarioBridge, 'revision_correctiva') && str_contains($funcionarioBridge, 'acta_satisfaccion') && str_contains($funcionarioBridge, 'acta_cotizacion') && str_contains($funcionarioBridge, 'source_flow') && str_contains($funcionarioBridge, 'scmqt_cotizacion'),
  'runtime consumes funcionario bridge links and opens native modals' => str_contains($runtimeJs, 'handleFuncionarioBridgeDeepLink') && str_contains($runtimeJs, 'openQuoteActionFromBridge') && str_contains($runtimeJs, 'openCaseButtonActionFromBridge') && str_contains($runtimeJs, 'openMaintenanceQuoteForm(bridgeSyntheticButton') && str_contains($runtimeJs, 'openSendCotizacionModal(sendBtn)') && str_contains($runtimeJs, 'openCotizacionOrderFormModal(orderBtn)') && str_contains($runtimeJs, 'clearFuncionarioBridgeParams'),
  'dashboard documents all wordpress bridge links with full app base' => str_contains($dashboard, 'scm-open-actas-guide') && str_contains($dashboard, "'baseUrl'") && str_contains($runtimeJs, 'openActasGuideModal') && str_contains($runtimeJs, 'runtime.baseUrl') && str_contains($runtimeJs, 'https://sucasainmobiliaria.com.co/control-servicios-inmobiliarios/public') && str_contains($runtimeJs, 'accion=acta_satisfaccion') && str_contains($runtimeJs, 'accion=acta_cotizacion') && str_contains($runtimeJs, 'accion=revision_correctiva') && str_contains($runtimeJs, 'accion=crear_cotizacion') && str_contains($runtimeJs, 'accion=editar_cotizacion') && str_contains($runtimeJs, 'accion=enviar_cotizacion') && str_contains($runtimeJs, 'accion=crear_orden') && str_contains($runtimeJs, 'tambi&eacute;n para crear-acta.php') && str_contains($runtimeJs, 'autologinSuffix'),
  'maintenance case cards carry preventive damage flag' => str_contains((string) file_get_contents($root . '/src/Modules/ServiciosInmobiliarios/Concerns/TableRowsConcern.php'), 'data-prev-encontro-danos') && str_contains((string) file_get_contents($root . '/src/Views/GenericTicketsCardView.php'), 'data-prev-encontro-danos') && str_contains((string) file_get_contents($root . '/src/Modules/Pending/PendingView.php'), 'data-prev-encontro-danos'),
  'case quote selector keeps modal cards styled outside app shell' => str_contains($runtimeJs, 'scm-case-cotizaciones-list') && str_contains($runtimeJs, 'scm-case-cotizacion-card') && str_contains($adminCss, '.scm-case-cotizaciones-modal .scm-cotizacion-card') && str_contains($adminCss, '.scm-case-cotizaciones-modal .scm-case-work-btn'),
  'case quote selector reopens after child modal actions' => str_contains($runtimeJs, 'makeCaseCotizacionesReturn') && str_contains($runtimeJs, 'reopenCaseCotizacionesAfter') && str_contains($runtimeJs, '_scmCaseCotizacionesReturn') && str_contains($runtimeJs, 'responseReturnContext.reopen') && str_contains($runtimeJs, 'approveReturnContext.reopen') && str_contains($runtimeJs, 'deleteReturnContext.reopen'),
  'case quote selector preserves ticket attributes across repeated reopens' => str_contains($runtimeJs, '"data-ticket-pk"') && str_contains($runtimeJs, '"data-ticket"') && str_contains($runtimeJs, 'attributes: Object.keys(attrs).map'),
  'quote cards only show response button after quote was sent' => str_contains($dashboard, '$cotizacionPuedeResponder = $cotizacionSinResponder && $enviada') && str_contains($dashboard, '$cotizacionPuedeResponder ? \'<button type="button" class="scm-case-work-btn" data-scm-cotizacion-response-standalone'),
  'approved quote act creation stays in system popup' => str_contains($dashboard, 'data-scm-create-cotizacion-acta') && str_contains($runtimeJs, 'openCotizacionActaFromCard') && str_contains($runtimeJs, 'data-scm-cotizacion-acta-button') && str_contains($runtimeJs, 'closeCurrentSwal') && str_contains($runtimeJs, 'window.Swal.close()') && !str_contains($dashboard, 'A&ntilde;adir acta</a>'),
  'quote cards expose native edit action only for editable quotes and hide legacy note action' => str_contains($dashboard, '$cotizacionEditable') && str_contains($dashboard, 'data-scm-edit-cotizacion') && str_contains($dashboard, 'data-cotizacion-mode="edit"') && !str_contains($dashboard, 'data-cotizacion-mode="note"') && !str_contains($dashboard, 'A&ntilde;adir nota') && !str_contains($dashboard, 'anadir-nota-a-cotizacion-de-mantenimiento') && str_contains($handler, 'No se puede editar una cotización desaprobada.'),
  'native quote popup renders repeaters and totals without iframe' => str_contains($runtimeJs, 'openMaintenanceQuoteForm') && str_contains($runtimeJs, 'renderCotizacionRepeaterRows') && str_contains($runtimeJs, 'syncMaintenanceQuoteTotals') && str_contains($runtimeJs, 'items_mano_json'),
  'native quote popup uses styled responsive form classes' => str_contains($runtimeJs, 'scm-maint-quote-form') && str_contains($runtimeJs, 'scm-maint-quote-section') && str_contains($adminCss, '.scm-maint-quote-form') && str_contains($adminCss, '.scm-maint-quote-row'),
  'native quote popup places conditions inside perturbation calculator after loaded data' => is_int($perturbDataBoxPos) && is_int($perturbConditionsPos) && is_int($perturbTypePos) && $perturbDataBoxPos < $perturbConditionsPos && $perturbConditionsPos < $perturbTypePos && str_contains($runtimeJs, 'data-quote-format') && str_contains($runtimeJs, 'formatMaintenanceQuotePlainNumber') && str_contains($runtimeJs, 'normalizeMaintenanceQuoteNumber') && str_contains($runtimeJs, 'inputmode="numeric"') && str_contains($runtimeJs, 'formatMaintenanceQuoteNumericInput(target)') && str_contains($adminCss, '.scm-maint-quote-conditions-box'),
  'native quote popup hides perturbation justification and keeps observations' => str_contains($runtimeJs, '<input type="hidden" name="justificacion_perturbacion"') && !str_contains($runtimeJs, '<span>Justificación</span><textarea name="justificacion_perturbacion"') && str_contains($runtimeJs, '<span>Observaciones</span><textarea name="observaciones"'),
  'native quote unit selector mirrors JetForm units and preserves legacy values' => str_contains($handler, 'maintenance_quote_unit_options') && str_contains($handler, "['value' => 'Und', 'label' => 'Und']") && str_contains($handler, "['value' => 'Jornal', 'label' => 'Jornal']") && str_contains($handler, "['value' => 'Lb', 'label' => 'Lb']") && str_contains($handler, 'maintenance_quote_merge_options($fallback, $options)') && str_contains($runtimeJs, 'if (!hasSelected && selectedValue)'),
  'native quote materials use extended material units only in generated support table' => str_contains($handler, 'material_unit_options') && str_contains($handler, 'maintenance_quote_material_unit_options') && str_contains($handler, "['value' => 'Cm', 'label' => 'Cm']") && str_contains($handler, "['value' => 'Galón', 'label' => 'Galón']") && str_contains($handler, "['value' => 'Cuñete', 'label' => 'Cuñete']") && str_contains($runtimeJs, 'type === "materiales_soporte" ? (context.material_unit_options || context.unit_options || [])'),
  'native quote popup syncs recipient from executor selection' => str_contains($runtimeJs, 'syncMaintenanceQuoteRecipient') && str_contains($runtimeJs, 'recipient_options') && str_contains($handler, 'maintenance_quote_recipient_options') && str_contains($handler, 'jet_cct_contratos_arrendamiento'),
  'native quote popup warns before replacing active quotes with sweetalert' => str_contains($runtimeJs, 'maintenanceQuoteWarningHtml') && str_contains($runtimeJs, 'confirmMaintenanceQuoteReplacement') && str_contains($runtimeJs, 'will_disapprove_previous') && str_contains($runtimeJs, 'quedará marcada como') && str_contains($runtimeJs, '<strong>Desaprobada</strong>') && str_contains($runtimeJs, 'Sí, crear nueva') && !str_contains($runtimeJs, 'window.confirm("Este caso ya tiene una cotización activa') && str_contains($adminCss, '.scm-swal-text-left') && str_contains($handler, 'maintenance_quote_existing_quotes_for_context'),
  'backend disapproves previous quotes on new quote creation' => str_contains($handler, 'maintenance_quote_disapprove_previous_quotes') && str_contains($handler, "'estado' => 'Desaprobada'") && str_contains($handler, 'Reemplazada por cotización #'),
  'quote save returns success with warnings when post-save steps fail' => str_contains($handler, '$postSaveWarnings') && str_contains($handler, 'Guardada con advertencias') && str_contains($handler, '[cotizacion_mantenimiento_save]'),
  'native quote real material repeater mirrors JetForm provider and value fields' => str_contains($runtimeJs, '["text", "provedor_materiales", "Proveedor"') && str_contains($runtimeJs, 'row.proveedor_materiales') && str_contains($runtimeJs, '["money", "valor_materiales", "Valor"') && str_contains($handler, "'proveedor_materiales'") && str_contains($runtimeJs, 'formData.append("items_materiales_json", JSON.stringify(collectQuoteRows(form, "materiales")))'),
  'native quote generated material support table creates offer image only' => str_contains($runtimeJs, 'materiales_soporte') && str_contains($runtimeJs, 'descripcion_materiales') && str_contains($runtimeJs, 'valor_unitario_materiales') && str_contains($runtimeJs, 'collectQuoteRows(form, "materiales_soporte")') && str_contains($runtimeJs, 'buildMaterialsQuoteImageDataUrl') && str_contains($runtimeJs, 'COTIZACIÓN MATERIAL') && str_contains($handler, 'maintenance_quote_store_generated_materials_image') && str_contains($storedFiles, 'storeImageDataUri'),
  'native quote material generator creates provider cards and real material rows' => str_contains($runtimeJs, 'data-generate-material-offer') && str_contains($runtimeJs, 'generateMaterialOfferFromSupport') && str_contains($runtimeJs, 'appendMaterialRowFromGeneratedOffer') && str_contains($runtimeJs, 'data-material-generated-offers') && str_contains($runtimeJs, 'data-generated-material-offer-row'),
  'native quote material image builder stays empty on edit and clears after delete' => str_contains($runtimeJs, 'function maintenanceQuoteMaterialSupportItems(items)') && str_contains($runtimeJs, 'return [{}];') && str_contains($runtimeJs, 'resetMaterialSupportBuilderIfNoSavedMaterials') && str_contains($runtimeJs, 'maintenanceQuoteHasSavedMaterialRows') && str_contains($runtimeJs, 'resetMaterialSupportBuilder(form);'),
  'native quote generated material images support multiple providers' => str_contains($runtimeJs, 'maintenanceQuoteGeneratedMaterialOffers') && str_contains($runtimeJs, 'JSON.stringify(generatedMaterialOffers)') && str_contains($handler, 'maintenance_quote_store_generated_materials_images') && str_contains($handler, 'foreach ($materialesOfertaImages as $materialesOfertaImage)') && str_contains($handler, 'array_slice($dataUris, 0, 10)'),
  'native quote generated material providers are synced into saved material rows' => str_contains($runtimeJs, 'syncMaintenanceQuoteGeneratedMaterialRows(form);') && str_contains($runtimeJs, 'appendMaterialRowFromGeneratedOffer(form, offer)') && str_contains($handler, 'maintenance_quote_merge_generated_material_rows') && str_contains($handler, 'maintenance_quote_generated_material_offer_rows') && str_contains($handler, "'provedor_materiales' => \$provider"),
  'backend ignores material auto item number as real material value' => str_contains($handler, "\$field !== 'item_materiales'") && str_contains($handler, 'if ($provider === \'\' && $total <= 0)'),
  'backend dedupes generated materials using fallback material value' => str_contains($handler, 'maintenance_quote_material_row_total') && str_contains($handler, '$total = $this->maintenance_quote_material_row_total($item)') && str_contains($handler, '$total = $this->maintenance_quote_material_row_total($row)') && str_contains($handler, '$clean[\'valor_total_materiales\'] = $clean[\'valor_materiales\']'),
  'native quote generated offer images are stored as local refs and resolved as signed urls' => str_contains($handler, 'maintenance_quote_stored_media_refs') && str_contains($handler, "\$refs[] = \$name") && str_contains($dashboard, 'cotizacion_local_file_name_from_ref') && str_contains($dashboard, '$storedFiles->urlFor($localName)') && str_contains($dashboard, "str_contains(\$part, 'file.php?')"),
  'native quote view marks missing stored offer files instead of broken images' => str_contains($dashboard, '$storedFiles->pathFor($localName) === null') && str_contains($dashboard, "'missing' => '1'") && str_contains($dashboard, 'El archivo ya no está en el almacenamiento') && str_contains($adminCss, '.scm-cotizacion-media-item.is-missing'),
  'backend keeps stored offer images if quote persisted after save warning' => str_contains($handler, 'maintenance_quote_persisted_after_error') && str_contains($handler, '$quotePersisted') && str_contains($handler, '$storedPhotos && !$quotePersisted') && str_contains($handler, 'Se detectó una advertencia posterior al guardado'),
  'native quote material rows are hidden and rendered from generated cards' => str_contains($runtimeJs, 'renderCotizacionHiddenRepeaterRows') && str_contains($runtimeJs, 'scm-maint-quote-hidden-repeater') && str_contains($runtimeJs, 'maintenanceQuoteGeneratedOfferByKey') && str_contains($runtimeJs, 'syncMaintenanceQuoteGeneratedMaterialRows') && str_contains($runtimeJs, 'data-remove-material-row-index') && str_contains($runtimeJs, 'materialKey') && str_contains($adminCss, '.scm-maint-quote-hidden-repeater'),
  'native quote generated material offers preview and appear under offer uploads' => str_contains($runtimeJs, 'data-material-generated-offer-attachments') && str_contains($runtimeJs, 'Subir mejores ofertas adicionales') && str_contains($runtimeJs, 'Mejores ofertas generadas por el sistema') && str_contains($runtimeJs, 'se guardarán automáticamente como mejores ofertas') && str_contains($runtimeJs, 'showMaintenanceQuoteMaterialImagePreview') && str_contains($runtimeJs, 'data-view-generated-material-offer') && str_contains($runtimeJs, 'scm-maint-quote-auto-offer-actions') && str_contains($runtimeJs, 'data-remove-generated-material-offer') && str_contains($adminCss, '.scm-maint-quote-auto-offer-card') && str_contains($adminCss, '.scm-maint-quote-auto-offer-actions') && str_contains($adminCss, '.scm-maint-quote-image-preview') && str_contains($adminCss, 'z-index: 2147483001'),
  'native quote popup keeps local draft and stays open on save errors' => str_contains($runtimeJs, 'maintenanceQuoteDraftKey') && str_contains($runtimeJs, 'saveMaintenanceQuoteDraft') && str_contains($runtimeJs, 'restoreMaintenanceQuoteDraft') && str_contains($runtimeJs, 'showMaintenanceQuoteDraftRestoredHint') && str_contains($runtimeJs, 'restoreMaintenanceQuotePerturbationSelections') && str_contains($runtimeJs, 'syncMaintenanceQuotePerturbation(form, context || {})') && str_contains($adminCss, '.scm-maint-quote-draft-hint') && str_contains($runtimeJs, '.setItem(draftKey, JSON.stringify(maintenanceQuoteDraftPayload(form, context || {})))') && str_contains($runtimeJs, 'showLoaderOnConfirm: true') && str_contains($runtimeJs, 'No se pudo guardar. Dejé tu progreso en pantalla y en borrador local.'),
  'native quote save success is not reverted by panel refresh failures' => str_contains($runtimeJs, 'Guardada, pero no se pudo refrescar el panel') && str_contains($runtimeJs, 'La cotización se guardó, pero no pude refrescar el panel') && str_contains($runtimeJs, 'return true;'),
  'active tab refresh resolves nested maintenance panels safely' => str_contains($runtimeJs, 'function refreshGenericTab(tabKey)') && str_contains($runtimeJs, 'activeKey = "preventivas_pendientes"') && str_contains($runtimeJs, 'openKey === "mant"') && str_contains($runtimeJs, 'return refreshGenericTab(openKey)') && str_contains($runtimeJs, 'return refreshGenericTab(statusKey)'),
  'native act creation keeps local draft on failures and reloads' => str_contains($ticketCompletionJs, 'actaDraftKey') && str_contains($ticketCompletionJs, 'saveActaDraft') && str_contains($ticketCompletionJs, 'restoreActaDraft') && str_contains($ticketCompletionJs, 'clearActaDraft') && str_contains($ticketCompletionJs, 'Restauré un borrador local del acta') && str_contains($ticketCompletionJs, 'saveActaDraft();') && str_contains($ticketCompletionJs, 'clearActaDraft();'),
  'native corrective review keeps local draft on failures and reloads' => str_contains($adminJs, 'correctiveDraftKey') && str_contains($adminJs, 'saveCorrectiveDraft') && str_contains($adminJs, 'restoreCorrectiveDraft') && str_contains($adminJs, 'clearCorrectiveDraft') && str_contains($adminJs, 'Restauré un borrador local de la revisión correctiva') && str_contains($adminJs, '_scmCorrectiveSaveDraft') && str_contains($adminJs, '_scmCorrectiveClearDraft'),
  'native quote material support items are automatic and not editable' => str_contains($runtimeJs, 'data-material-auto-item') && str_contains($runtimeJs, 'refreshMaterialAutoItems') && str_contains($runtimeJs, 'if (type === "materiales_soporte") obj.item_materiales = String(index + 1)') && !str_contains($runtimeJs, '["number", "item_materiales", "Ítem"'),
  'native quote material generator CSS separates real materials from support spreadsheet' => str_contains($adminCss, '[data-quote-repeater="materiales"] .scm-maint-quote-row') && str_contains($adminCss, '[data-quote-repeater="materiales_soporte"] .scm-maint-quote-row') && str_contains($adminCss, '.scm-maint-quote-generated-card') && str_contains($adminCss, '.scm-maint-quote-support-head'),
  'native quote material offers render below generated material image support' => is_int($materialsRepeaterPos) && is_int($materialsSupportRepeaterPos) && is_int($generatedMaterialsPos) && is_int($offersSectionPos) && is_int($equipmentRepeaterPos) && $materialsRepeaterPos < $materialsSupportRepeaterPos && $materialsSupportRepeaterPos < $generatedMaterialsPos && $generatedMaterialsPos < $offersSectionPos && $offersSectionPos < $equipmentRepeaterPos && !str_contains($runtimeJs, '<section class="scm-maint-quote-section"><h4>Soportes</h4>'),
  'native quote view renders simple materials before offers and labor' => is_int($nativeMaterialBudgetPos) && is_int($nativeMaterialOffersPos) && is_int($nativeLaborBudgetPos) && $nativeMaterialBudgetPos < $nativeMaterialOffersPos && $nativeMaterialOffersPos < $nativeLaborBudgetPos && str_contains($dashboard, 'render_cotizacion_materials_budget_rows') && str_contains($dashboard, 'Proveedor / material') && str_contains($dashboard, 'scm-cotizacion-materials-table') && str_contains($adminCss, '.scm-cotizacion-native-material-offers') && str_contains($adminCss, '.scm-cotizacion-materials-table'),
  'native quote value lookup skips empty fields and respects field priority' => str_contains($dashboard, 'foreach ($needles as $needle)') && str_contains($dashboard, 'foreach ($item as $key => $value)') && str_contains($dashboard, '$cleanValue = $this->cotizacion_clean_text($value)') && str_contains($dashboard, 'if ($cleanValue !== \'\')') && str_contains($dashboard, 'return $cleanValue;'),
  'native quote view and pdf read legacy misspelled equipment and other cost descriptions' => str_contains($dashboard, "'descipcion', 'descripcion'") && str_contains($handler, "'descipcion', 'descripcion'") && str_contains($runtimeJs, 'descipcion_otros_equi') && str_contains($runtimeJs, 'descipcion_otros_costos'),
  'native quote view calculates line totals from quantity and unit value' => str_contains($dashboard, 'cotizacion_parse_budget_number') && str_contains($dashboard, "['cantidad_otros_equi', 'valor_otros_equi']") && str_contains($dashboard, "['cantidad_otros_costos', 'valor_otros_costos']") && str_contains($dashboard, "['cantidad_mano', 'valor_mano']") && str_contains($dashboard, 'if ($parsed > 0)'),
  'native quote view uses corporate brand name' => str_contains($dashboard, 'SKC SuCasa Inmobiliaria') && !str_contains($dashboard, '<strong>SuCasa Inmobiliaria</strong><span>Control Servicios Inmobiliarios</span>'),
  'case quote list hides ticket and note actions but keeps finance toggles' => str_contains($dashboard, 'data-scm-open-linked-ticket-case data-ticket-pk="') && str_contains($dashboard, '>Ver caso</button>') && str_contains($runtimeJs, 'prepareCaseCotizacionCardForModal') && str_contains($runtimeJs, '.scm-cotizacion-actions [data-scm-open-linked-ticket-case]') && str_contains($runtimeJs, '.scm-cotizacion-actions .scm-btn-case') && str_contains($runtimeJs, '[data-cotizacion-mode="note"]') && str_contains($runtimeJs, 'toggleCotizacionFinancePanel(financeBtn)'),
  'history quote buttons open native quote view instead of WordPress iframe' => str_contains($genericTicketsUi, 'cotizacionMantenimientoIdFromUrl') && str_contains($historyPresentation, 'cotizacionMantenimientoIdFromUrl') && str_contains($genericTicketsUi, 'data-scm-view-cotizacion-native data-cotizacion-id') && str_contains($historyPresentation, 'data-scm-view-cotizacion-native data-cotizacion-id') && str_contains($genericTicketsUi, 'cotizacion-de-mantenimiento') && str_contains($genericTicketsUi, 'cotizacion-mantenimiento.php') && str_contains($historyPresentation, 'cotizacion-de-mantenimiento') && str_contains($historyPresentation, 'cotizacion-mantenimiento.php'),
  'native quote popup calculates perturbation without legacy shortcode' => str_contains($runtimeJs, 'maintenanceQuotePerturbationHtml') && str_contains($runtimeJs, 'syncMaintenanceQuotePerturbation') && str_contains($runtimeJs, 'dias_afectacion_calculados') && str_contains($handler, 'maintenance_quote_perturbation_context'),
  'native perturbation calculator matches legacy guided sections' => str_contains($runtimeJs, 'Calculadora de perturbación del inmueble') && str_contains($runtimeJs, '0. Tipo de valoración') && str_contains($runtimeJs, '1. Días de afectación calculados') && str_contains($runtimeJs, '2. Criterios de severidad') && str_contains($runtimeJs, '3. Responsabilidad probable') && str_contains($runtimeJs, 'Datos cargados desde inmuebles') && str_contains($runtimeJs, 'box.setAttribute("data-quote-perturb-type", type)') && str_contains($adminCss, '.scm-maint-quote-days-box') && str_contains($adminCss, '.scm-maint-quote-result-card') && str_contains($adminCss, '.scm-maint-quote-criteria-grid[hidden]') && str_contains($adminCss, '.scm-maint-quote-criterion-card[hidden]'),
  'native perturbation calculator persists dynamic select values' => str_contains($runtimeJs, 'Selecciona tipo de valoración') && str_contains($runtimeJs, 'Selecciona actividad comercial') && str_contains($runtimeJs, 'criterios_valores') && str_contains($runtimeJs, 'tipo_valoracion_key') && str_contains($runtimeJs, 'actividad_comercial_key') && str_contains($runtimeJs, 'savedCriteria[name]') && str_contains($runtimeJs, 'criteriaValues[key] = select.value'),
  'native perturbation calculator includes in-popup guides' => str_contains($runtimeJs, 'quotePerturbationGuideContent') && str_contains($runtimeJs, 'showMaintenanceQuoteGuide') && str_contains($runtimeJs, 'data-quote-guide-key="general"') && str_contains($runtimeJs, 'data-quote-guide-panel') && str_contains($adminCss, '.scm-maint-quote-guide-panel'),
  'quote timestamps prefer WordPress local time' => str_contains($handler, 'maintenance_quote_now_pair') && str_contains($handler, "current_time('mysql')"),
  'native quote repeater add buttons use styled controls' => str_contains($runtimeJs, 'scm-maint-quote-add') && str_contains($adminCss, '.scm-maint-quote-add'),
  'backend saves quote modes and revision quote flag' => str_contains($handler, 'maintenance_quote_mode') && str_contains($handler, "'categoria_cotizacion' => \$category") && str_contains($handler, 'maintenance_quote_update_revision_flag') && str_contains($handler, "'tiene_cotizacion' => 'Si'"),
  'backend creates or updates one administrative report from active maintenance quote' => str_contains($handler, 'maintenance_quote_ensure_admin_report') && str_contains($handler, "jet_cct_reportes_administrativos") && str_contains($handler, "'id_cotizacion_mantenimiento' => (string) \$quoteId") && str_contains($handler, "'categoria' => \$reportCategory") && str_contains($handler, "\$existingReportId") && str_contains($handler, "unset(\$reportUpdate['cct_created']"),
  'administrative report is not limited to corrective quotes' => str_contains($handler, "if (\$mode === 'create')") && str_contains($handler, 'maintenance_quote_ensure_admin_report') && str_contains($handler, 'id_revision_preventiva'),
  'backend enqueues configurable quote notifications' => str_contains($app, 'cotizacion_mantenimiento_guardada') && str_contains($handler, 'maintenance_quote_enqueue_saved_notifications') && str_contains($handler, "'source_module' => 'cotizaciones_mantenimiento'") && str_contains($handler, 'EmailQueue'),
  'quote saved email uses corporate template banner and signed public link' => str_contains($handler, 'EmailTemplate::render($subject, $content') && str_contains($handler, 'signedMaintenanceQuotePublicUrl($quoteId)') && str_contains($app, 'signedMaintenanceQuotePublicUrl') && str_contains($app, 'maintenanceQuotePublicSignatureValid'),
  'public maintenance quote page requires session or signed non enumerable link' => str_contains($publicQuote, 'maintenanceQuotePublicSignatureValid') && str_contains($publicQuote, 'Auth::isLoggedIn()') && str_contains($publicQuote, 'render_public_cotizacion_mantenimiento') && str_contains($publicQuote, 'X-Robots-Tag: noindex, nofollow') && str_contains($publicQuote, 'SCM_DEFAULT_PORTAL_LOGO_URL'),
  'public maintenance quote page can save signed quote responses' => str_contains($publicQuote, 'scm_public_quote_response') && str_contains($publicQuote, 'public_respond_cotizacion_mantenimiento') && str_contains($dashboard, 'render_public_cotizacion_response_panel') && str_contains($dashboard, 'Responder cotización') && str_contains($handler, 'public_respond_cotizacion_mantenimiento') && str_contains($publicQuote, "form-action 'self'"),
  'backend loads quote glossary options from JetEngine glossaries' => str_contains($handler, 'maintenance_quote_glossary_options(612') && str_contains($handler, 'maintenance_quote_glossary_options(853') && str_contains($handler, 'correctiveReviewGlossaryOptions'),
  'backend validates quote support images before saving' => str_contains($handler, 'maintenance_quote_store_media') && str_contains($handler, 'handleImageUploadsDetailed') && str_contains($handler, 'supera 1.5 MB'),
  'native quote support media accepts ids urls and local names' => str_contains($dashboard, 'cotizacion_split_media_refs($row[\'mejor_oferta\'] ?? \'\')') && str_contains($dashboard, 'cotizacion_split_media_refs($row[\'otras_oferta\'] ?? \'\')') && str_contains($handler, 'cotizacion_split_media_refs($row[\'mejor_oferta\'] ?? \'\')') && str_contains($handler, 'cotizacion_split_media_refs($row[\'otras_oferta\'] ?? \'\')'),
  'media migrator defaults to dry run and handles php serialized data' => str_contains($mediaMigrator, 'array_key_exists(\'apply\', $options)') && str_contains($mediaMigrator, 'unserialize($raw, [\'allowed_classes\' => false])') && str_contains($mediaMigrator, "'jet_cct_cotizacion_mantenimiento'") && str_contains($mediaMigrator, "'mejor_oferta'"),
  'approved quote cards expose native add order action' => str_contains($dashboard, '$cotizacionAprobada ?') && str_contains($dashboard, 'data-scm-add-cotizacion-order') && !str_contains($dashboard, 'anadir-orden-de-mantenimiento'),
  'approved quote cards block add order when active act exists' => str_contains($dashboard, '$hasActiveActa') && str_contains($dashboard, 'Orden bloqueada por acta') && str_contains($dashboard, 'cotizacion_satisfaction_act_info($id, trim((string) ($row[\'id_acta_satisfaccion\'] ?? \'\')), $ticket)'),
  'native add order popup loads context and saves without iframe' => str_contains($runtimeJs, 'openCotizacionOrderFormModal') && str_contains($runtimeJs, 'actionCotizacionOrderContext') && str_contains($runtimeJs, 'actionCotizacionOrderSave') && str_contains($runtimeJs, '[data-scm-add-cotizacion-order]'),
  'native order response popup updates pending orders without iframe' => str_contains($runtimeJs, 'openCotizacionOrderResponseModal') && str_contains($runtimeJs, 'actionCotizacionOrderResponse') && str_contains($runtimeJs, '[data-scm-respond-cotizacion-order]') && str_contains($dashboard, 'Responder orden'),
  'native order response popup uses semantic approve/reject colors' => str_contains($runtimeJs, 'scm-cotizacion-order-response-confirm') && str_contains($runtimeJs, 'is-success') && str_contains($runtimeJs, 'is-danger') && str_contains($adminCss, '.scm-cotizacion-order-response-confirm.is-success') && str_contains($adminCss, '.scm-cotizacion-order-response-confirm.is-danger'),
  'backend blocks maintenance orders when quote or case has active act' => str_contains($handler, 'maintenance_order_active_satisfaction_act') && str_contains($handler, 'ya tiene un acta de satisfaccion activa'),
  'backend prevents orders above available balance' => str_contains($handler, '$value > ($currentBalance + 0.01)') && str_contains($handler, 'El valor supera el saldo disponible'),
  'backend recalculates edited quote balances from real maintenance orders' => str_contains($handler, 'maintenance_quote_order_used_balances') && str_contains($handler, "jet_cct_ordenes") && str_contains($handler, "TRIM(COALESCE(`id_cotizacion`, '')) = ?") && str_contains($handler, '$usedBalances[\'saldo_materiales\'] ?? null') && str_contains($handler, '?float $usedOverride = null'),
  'backend resets edited quote to unsent without response state' => str_contains($handler, "'se_envio' => 'No'") && str_contains($handler, "'estado' => ''") && str_contains($handler, "'estado_respuesta_cotizacion_mantenimiento' => ''") && str_contains($handler, "'fecha_respuesta' => 0") && str_contains($handler, "'fecha_envio' => 0") && str_contains($handler, "'fue_enviada_cotizacion_mantenimiento' => 'No'") && str_contains($handler, "'fecha_respuesta_cotizacion_mantenimiento' => 0"),
  'frontend create quote ignores previous quote id and can clear old create draft' => str_contains($runtimeJs, 'resolvedMode === "create" ? ""') && str_contains($runtimeJs, 'data-scm-clear-cotizacion-create-draft') && str_contains($runtimeJs, 'clearMaintenanceQuoteDraft(draftKey)'),
  'backend creates and responds orders through shared notification queue' => str_contains($handler, 'maintenance_order_enqueue_created_notifications') && str_contains($handler, 'maintenance_order_enqueue_response_notifications') && str_contains($handler, "new \\SCM\\Support\\EmailQueue") && str_contains($handler, "'source_module' => 'ordenes_mantenimiento'"),
  'internal notification settings include maintenance order events' => str_contains($app, 'orden_mantenimiento_creada') && str_contains($app, 'respuesta_orden_mantenimiento') && str_contains($app, 'Email interno en cola'),
  'backend accepts responses only for pending orders' => str_contains($handler, 'ajax_handler_cotizacion_order_response') && str_contains($handler, "Solo puedes responder una orden que este esperando respuesta.") && str_contains($handler, 'maintenance_order_insert_response_histories'),
  'order notification email uses signed public response link' => str_contains($handler, 'orden-publica.php') && str_contains($handler, 'maintenance_order_public_signature') && str_contains($handler, 'public_cotizacion_order_signature_valid'),
  'public order response page approves without panel login' => str_contains($publicOrder, 'public_respond_cotizacion_order') && str_contains($publicOrder, 'Respuesta de orden de mantenimiento') && str_contains($publicOrder, 'Aprobar orden') && str_contains($publicOrder, 'Desaprobar orden'),
  'public order response page has dedicated responsive styles' => str_contains($publicOrderCss, '.scm-order-public-shell') && str_contains($publicOrderCss, '.scm-order-public-button') && str_contains($publicOrderCss, '@media (max-width: 760px)'),
  'frontend warns before submitting order above balance' => str_contains($runtimeJs, 'value > balance') && str_contains($runtimeJs, 'El valor supera el saldo disponible'),
  'frontend validates quote order amount live' => str_contains($runtimeJs, 'validateOrderAmount') && str_contains($runtimeJs, 'data-scm-order-value-error') && str_contains($runtimeJs, 'confirmButton.disabled = isOver') && str_contains($adminCss, '.scm-cotizacion-order-balance.is-over') && str_contains($adminCss, '.scm-cotizacion-order-value-error'),
  'backend creates maintenance orders from approved quotes' => str_contains($handler, 'ajax_handler_cotizacion_order_save') && str_contains($handler, "jet_cct_ordenes") && str_contains($handler, 'maintenance_order_update_cotizacion_balance') && str_contains($handler, 'maintenance_order_insert_histories') && str_contains($handler, 'maintenance_order_save_provider'),
  'backend reuses existing maintenance order providers before creating duplicates' => str_contains($handler, 'maintenance_order_find_existing_provider_id') && str_contains($handler, 'identificacion_proveedor') && str_contains($handler, 'LOWER(TRIM(`correo_proveedor`))') && str_contains($handler, 'preg_replace') && str_contains($handler, 'celular_proveedor'),
  'backend sends maintenance order approval link to configured officials by whatsapp' => str_contains($handler, 'maintenance_order_internal_whatsapp_recipients') && str_contains($handler, 'maintenance_order_enqueue_created_whatsapp') && str_contains($handler, 'scm_orden_mantenimiento_funcionario_v1') && str_contains($handler, 'orden-mantenimiento-creada-whatsapp') && str_contains($handler, 'button_url_mode') && str_contains($funcionarioOptions, "'phone'") && str_contains($orderOfficialTemplate, 'scm_orden_mantenimiento_funcionario_v1'),
  'native add order popup uses styled form classes' => str_contains($runtimeJs, 'scm-cotizacion-order-form') && str_contains($runtimeJs, 'scm-cotizacion-order-grid') && str_contains($adminCss, '.scm-cotizacion-order-form') && str_contains($adminCss, '.scm-cotizacion-order-grid'),
  'ticket response carries exact quote id when available' => str_contains($adminJs, 'name="id_cotizacion"') && str_contains($adminJs, 'caseBtn.dataset.cotizacionId'),
  'standalone quote response carries exact quote id' => str_contains($runtimeJs, 'fd.append(') && str_contains($runtimeJs, '"id_cotizacion"') && str_contains($runtimeJs, 'responseBtn.getAttribute("data-cotizacion-id")'),
  'backend validates targeted quote belongs to ticket' => str_contains($workflow, '$targetCotizacionId > 0') && str_contains($workflow, 'La cotizacion seleccionada no pertenece a este ticket.'),
  'backend rejects state changes for decided quotes' => str_contains($workflow, 'Solo se puede cambiar una cotizacion sin estado o en Esperando respuesta.') && str_contains($handler, 'Solo se puede marcar como aprobada una cotizacion sin estado o en Esperando respuesta.') && str_contains($handler, 'Solo se puede eliminar/desaprobar una cotizacion sin estado o en Esperando respuesta.'),
  'app defines repair followup notice action' => str_contains($app, 'AJAX_REPAIR_FOLLOWUP_NOTICE') && str_contains($app, 'scm_seguimiento_reparaciones_cotizacion'),
  'router maps repair followup notice action' => str_contains($router, 'AJAX_REPAIR_FOLLOWUP_NOTICE') && str_contains($router, 'ajax_handler_repair_followup_notice'),
  'runtime exposes repair followup notice action' => str_contains($dashboard, "'repair_followup_notice' => self::AJAX_REPAIR_FOLLOWUP_NOTICE"),
  'case and quote cards expose repair followup only after 10 calendar days' => str_contains($adminJs, 'caseCanGenerateRepairFollowup') && str_contains($dashboard, '$diasCalendarioSinRespuesta > 10') && str_contains($dashboard, 'data-scm-repair-followup-notice'),
  'repair followup popup uses automatic history text only' => !str_contains($adminJs, 'Observaci&oacute;n para el historial') && !str_contains($runtimeJs, 'swal-repair-followup-observacion'),
  'backend validates exact quote and 10 calendar days before generating repair followup' => str_contains($workflow, 'generateRepairFollowupNotice') && str_contains($workflow, 'cotizacionBelongsToTicket') && str_contains($workflow, 'elapsedCalendarDays') && str_contains($workflow, '$elapsedDays <= 10'),
  'repair followup pdf uses SuCasa letterhead and corporate name' => str_contains($ticketPdf, 'generateRepairFollowupNotice') && str_contains($ticketPdf, "backgroundImage(\$this->letterheadPath())") && str_contains($ticketPdf, 'Seguimiento de reparaciones') && str_contains($ticketPdf, 'SKC SuCasa Inmobiliaria'),
  'repair followup stores ticket document and history' => str_contains($workflow, 'generateRepairFollowupNotice') && str_contains($workflow, 'insertHistorial(') && str_contains($workflow, 'uniqueTicketDocuments($ticketDocs)'),
  'repair followup stores property history report with attachment' => str_contains($workflow, 'insertRepairFollowupPropertyHistory') && str_contains($workflow, "jet_cct_historial_del_inmueble") && str_contains($workflow, "'tipo_reporte' => 'Seguimiento de reparaciones'") && str_contains($workflow, "'archivos' => \$documents") && str_contains($workflow, "'property_history_saved'"),
  'repair followup enqueues shared email and whatsapp notifications' => str_contains($notificationDelivery, 'notifyRepairFollowupNotice') && str_contains($notificationDelivery, "'source_module' => 'seguimiento_reparaciones_cotizacion'") && str_contains($notificationDelivery, 'scm_seguimiento_reparaciones_v1') && str_contains($notificationDelivery, 'SmsQueue'),
  'repair followup whatsapp button sends dynamic suffix expected by Meta' => str_contains($notificationDelivery, '$buttonSuffix = $this->whatsappUrlButtonSuffix($noticeUrl)') && str_contains($notificationDelivery, "'button_url_mode' => 'dynamic_suffix'") && str_contains($notificationDelivery, "['type' => 'text', 'text' => \$buttonSuffix]"),
  'repair followup whatsapp template documents url placeholder without encoded braces' => str_contains($repairFollowupTemplate, 'https://sucasainmobiliaria.com.co/{{1}}') && !str_contains($repairFollowupTemplate, '%7B%7B1%7D%7D'),
];

$failed = [];
foreach ($checks as $label => $ok) {
  if (!$ok) {
    $failed[] = $label;
  }
}

if ($failed) {
  fwrite(STDERR, "Cotizaciones mantenimiento checks failed:\n- " . implode("\n- ", $failed) . "\n");
  exit(1);
}

echo 'Cotizaciones mantenimiento checks passed: ' . count($checks) . PHP_EOL;
