<?php
use SCM\Modules\Pending\PublicServicesUi as UI;
use SCM\Modules\Pending\PublicServicesActTemplates as Templates;
$e=[SCM\Modules\Pending\PublicServicesDocument::class,'e'];
?>
<div class="<?= UI::CARD ?> !sp-font-sans !sp-text-service-navy">
<header class="!sp-bg-slate-50/60 !sp-p-6 !sp-border-b !sp-border-solid !sp-border-slate-100 !sp-flex !sp-flex-col md:!sp-flex-row md:!sp-items-center !sp-justify-between !sp-gap-4"><div><span class="!sp-text-[10px] !sp-font-bold !sp-uppercase !sp-tracking-wide !sp-text-service-blue">Configuración de documentos oficiales</span><h3 class="!sp-m-0 !sp-mt-1 !sp-font-extrabold !sp-text-xl !sp-uppercase">Contenido de las actas</h3></div><div class="!sp-flex !sp-gap-3 !sp-items-center !sp-bg-amber-50 !sp-border !sp-border-solid !sp-border-amber-200 !sp-rounded-xl !sp-p-3 !sp-max-w-lg !sp-text-[10px] !sp-leading-relaxed !sp-text-amber-900"><?= UI::icon('alert') ?><p class="!sp-m-0"><strong>Nota de auditoría:</strong> Los cambios se aplican a las próximas revisiones. Las actas ya emitidas conservan su contenido y PDF original.</p></div></header>
<form data-services-template-form class="!sp-p-6 !sp-space-y-6"><input type="hidden" name="version" value="<?= $e($template['version']) ?>">
<div class="!sp-grid !sp-grid-cols-1 md:!sp-grid-cols-3 !sp-gap-5"><label><span class="<?= UI::LABEL ?>">Tipo de acta <b class="!sp-text-rose-500">*</b></span><select class="<?= UI::INPUT ?> !sp-font-semibold" name="type" data-services-template-type data-loaded-type="<?= $e($type) ?>"><?php foreach(Templates::TYPES as $key=>$label): ?><option value="<?= $key ?>" <?= $key===$type?'selected':'' ?>><?= $e($label) ?></option><?php endforeach ?></select><small class="!sp-block !sp-mt-2 !sp-text-[10px] !sp-text-service-muted">Asociada al dictamen de pago y solvencia del inmueble.</small></label><label class="md:!sp-col-span-2"><span class="<?= UI::LABEL ?>">Título del acta <b class="!sp-text-rose-500">*</b></span><div class="!sp-relative"><input class="<?= UI::INPUT ?> !sp-font-semibold !sp-pr-28" name="title" maxlength="240" required value="<?= $e($template['title']) ?>"><span class="!sp-absolute !sp-right-2 !sp-top-3 !sp-text-[8px] !sp-font-bold !sp-uppercase !sp-bg-slate-200 !sp-rounded !sp-px-1.5 !sp-py-0.5 !sp-pointer-events-none">Cabecera PDF</span></div><small class="!sp-block !sp-mt-2 !sp-text-[10px] !sp-text-service-muted">Encabezado principal visible al inicio del informe generado para arrendatarios.</small></label></div>
<div><div class="!sp-flex !sp-items-center !sp-justify-between !sp-mb-2"><label for="services-template-body" class="<?= UI::LABEL ?> !sp-mb-0">Contenido del acta <b class="!sp-text-rose-500">*</b></label><div class="!sp-flex !sp-items-center !sp-gap-1 !sp-bg-slate-100 !sp-rounded-lg !sp-p-1 !sp-border !sp-border-solid !sp-border-slate-200"><button type="button" class="!sp-px-2 !sp-py-1 !sp-border-0 !sp-bg-transparent !sp-font-bold !sp-text-xs !sp-text-service-navy !sp-cursor-pointer" data-services-template-format="bold" title="Negrita" aria-label="Negrita">B</button><button type="button" class="!sp-px-2 !sp-py-1 !sp-border-0 !sp-bg-transparent !sp-italic !sp-text-xs !sp-text-service-navy !sp-cursor-pointer" data-services-template-format="italic" title="Cursiva" aria-label="Cursiva">I</button><button type="button" class="!sp-px-2 !sp-py-1 !sp-border-0 !sp-bg-transparent !sp-underline !sp-text-xs !sp-text-service-navy !sp-cursor-pointer" data-services-template-format="underline" title="Subrayado" aria-label="Subrayado">U</button><button type="button" class="<?= UI::SECONDARY ?> !sp-text-[10px]" data-services-show-variables>&lt;/&gt; Variables</button></div></div><textarea id="services-template-body" name="body" rows="8" maxlength="20000" required class="!sp-box-border !sp-w-full !sp-min-h-[220px] !sp-p-4 !sp-bg-white !sp-border-2 !sp-border-solid !sp-border-service-yellow !sp-rounded-xl !sp-text-xs !sp-leading-relaxed !sp-text-service-navy !sp-font-sans !sp-resize-y focus:!sp-outline-none focus:!sp-ring-2 focus:!sp-ring-service-yellow"><?= $e($template['body']) ?></textarea></div>
<div data-services-variables><p class="!sp-m-0 !sp-mb-3 !sp-text-[10px] !sp-text-service-muted"><strong class="!sp-text-service-navy">Variables disponibles:</strong> selecciona una para insertarla en el contenido.</p><div class="!sp-flex !sp-flex-wrap !sp-gap-2"><?php foreach(Templates::VARIABLES as $variable): ?><button type="button" class="!sp-px-2 !sp-py-1.5 !sp-rounded !sp-text-[10px] !sp-font-mono !sp-bg-blue-50 !sp-text-service-blue !sp-border !sp-border-solid !sp-border-blue-200 !sp-cursor-pointer hover:!sp-bg-service-yellow focus-visible:!sp-ring-2 focus-visible:!sp-ring-service-blue" data-services-variable="{{<?= $variable ?>}}">{{<?= $variable ?>}}</button><?php endforeach ?></div></div>
<footer class="!sp-flex !sp-justify-between !sp-gap-3 !sp-border-x-0 !sp-border-b-0 !sp-border-t !sp-border-solid !sp-border-slate-100 !sp-pt-5"><button type="button" class="<?= UI::SECONDARY ?>" data-services-template-preview><?= UI::icon('eye') ?>Vista previa</button><button type="submit" class="<?= UI::PRIMARY ?>"><?= UI::icon('document') ?>Guardar plantilla</button></footer>
</form></div>
