<?php
use SCM\Modules\Pending\PublicServicesUi as UI;
use SCM\Modules\Pending\PublicServicesWorkspace as Workspace;
use SCM\Modules\Pending\PublicServicesDocument as Document;
$e=[Document::class,'e'];
?>
<div class="!sp-font-sans !sp-text-service-navy !sp-space-y-5" data-services-history>
<div class="<?= UI::CARD ?> !sp-p-5"><header class="!sp-flex !sp-justify-between !sp-items-center !sp-gap-3 !sp-border-t-0 !sp-border-x-0 !sp-border-b !sp-border-solid !sp-border-slate-100 !sp-pb-3 !sp-mb-4"><h3 class="!sp-m-0 !sp-text-[10px] !sp-font-semibold !sp-uppercase !sp-flex !sp-gap-2 !sp-items-center"><?= UI::icon('filter') ?>Filtros de búsqueda de revisiones</h3><span class="!sp-text-[10px] !sp-text-service-muted">Refina tus resultados aplicando uno o más filtros</span></header><form data-services-history-form><div class="!sp-grid !sp-grid-cols-1 sm:!sp-grid-cols-2 lg:!sp-grid-cols-6 !sp-gap-3">
<?php foreach(['contrato'=>'Contrato','inmueble'=>'Inmueble SIMI','arrendatario'=>'Arrendatario','propietario'=>'Propietario','from'=>'Desde','to'=>'Hasta'] as $key=>$label): ?><label><span class="<?= UI::LABEL ?>"><?= $label ?></span><input class="<?= UI::INPUT ?>" name="<?= $key ?>" type="<?= in_array($key,['from','to'],true)?'date':'text' ?>" value="<?= $e($input[$key]??'') ?>" placeholder="<?= in_array($key,['contrato','inmueble'])?'Ej: 780':'Buscar por nombre...' ?>"></label><?php endforeach ?></div>
<div class="!sp-flex !sp-flex-wrap !sp-justify-between !sp-gap-3 !sp-mt-4"><div class="!sp-flex !sp-gap-2"><button type="submit" class="<?= UI::PRIMARY ?>"><?= UI::icon('filter') ?>Filtrar</button><button type="button" class="<?= UI::SECONDARY ?>" data-services-history-clear>Limpiar filtros</button></div><button type="button" class="<?= UI::SECONDARY ?>" data-services-export="history" title="Exportar la página actual a CSV compatible con Excel"><?= UI::icon('download') ?>Exportar Excel</button></div>
<input type="hidden" name="order" value="<?= $e($input['order']??'desc') ?>"></form></div>
<div class="<?= UI::CARD ?>"><header class="!sp-flex !sp-flex-wrap !sp-items-center !sp-justify-between !sp-gap-3 !sp-p-5 !sp-bg-slate-50/50"><div><h3 class="!sp-m-0 !sp-text-sm !sp-font-bold">Historial de revisiones realizadas</h3><p class="!sp-m-0 !sp-mt-1 !sp-text-[10px] !sp-text-service-muted">Mostrando <?= $total ?> revisiones registradas en el sistema · Página <?= $page ?> de <?= $pages ?></p></div><label class="!sp-flex !sp-items-center !sp-gap-2 !sp-text-[10px] !sp-text-service-muted">Ordenar por: <select class="<?= UI::INPUT ?> !sp-w-44" data-services-history-order><option value="desc" <?= ($input['order']??'desc')==='desc'?'selected':'' ?>>Más recientes primero</option><option value="asc" <?= ($input['order']??'desc')==='asc'?'selected':'' ?>>Más antiguas primero</option></select></label></header>
<div class="!sp-overflow-x-auto"><table class="!sp-w-full !sp-min-w-[1050px] !sp-border-collapse !sp-text-[10px]" data-services-history-table><thead class="!sp-bg-slate-50"><tr><?php foreach(['Revisión','Fecha','Contrato / Inmueble','Dirección / Arrendatario','Realizado por','Acciones y actas emitidas'] as $label): ?><th class="!sp-px-4 !sp-py-3 !sp-text-left !sp-text-[9px] !sp-uppercase !sp-tracking-wide !sp-font-semibold !sp-text-service-muted !sp-border-x-0 !sp-border-y !sp-border-solid !sp-border-slate-200"><?= $label ?></th><?php endforeach ?></tr></thead><tbody>
<?php foreach($rows as $row): $url=Document::url((int)$row['_ID']); ?>
<tr class="!sp-border-t-0 !sp-border-x-0 !sp-border-b !sp-border-solid !sp-border-slate-100 hover:!sp-bg-slate-50"><td class="!sp-border-x-0 !sp-border-y-0 !sp-px-4 !sp-py-4"><span class="!sp-bg-slate-100 !sp-border !sp-border-solid !sp-border-slate-200 !sp-rounded !sp-px-2 !sp-py-1 !sp-font-bold">#<?= $e($row['_ID']) ?></span></td><td class="!sp-border-x-0 !sp-border-y-0 !sp-px-4 !sp-py-4 !sp-whitespace-nowrap"><?= UI::date($row['fecha']??'') ?></td><td class="!sp-border-x-0 !sp-border-y-0 !sp-px-4 !sp-py-4"><strong class="!sp-block">#Contrato: <?= $e($row['contrato']??'Sin registrar') ?></strong><small class="!sp-text-service-muted">SIMI: <?= $e($row['inmueble']??'Sin registrar') ?></small></td><td class="!sp-border-x-0 !sp-border-y-0 !sp-px-4 !sp-py-4 !sp-max-w-[260px]"><span class="!sp-block"><?= $e($row['direccion']??'') ?></span><small class="!sp-block !sp-mt-1 !sp-text-service-muted"><?= $e($row['arrendatario']??'') ?></small></td><td class="!sp-border-x-0 !sp-border-y-0 !sp-px-4 !sp-py-4"><div class="!sp-flex !sp-gap-2 !sp-items-center"><span class="!sp-p-2 !sp-bg-slate-100 !sp-rounded-full"><?= UI::icon('user','!sp-w-3 !sp-h-3') ?></span><strong class="!sp-max-w-[150px]"><?= $e($row['realizado_por']??'Sin registrar') ?></strong></div></td><td class="!sp-border-x-0 !sp-border-y-0 !sp-px-4 !sp-py-4"><div class="!sp-flex !sp-flex-wrap !sp-justify-end !sp-gap-2"><button type="button" class="<?= UI::NAVY ?>" data-scm-open-iframe data-iframe-url="<?= $e($url) ?>" data-iframe-title="Revisión de servicios públicos"><?= UI::icon('eye','!sp-w-3 !sp-h-3 !sp-text-service-yellow') ?>Ver revisión</button><button type="button" class="<?= UI::SECONDARY ?> !sp-text-[10px]" aria-label="Copiar enlace público" data-services-copy-url="<?= $e($url) ?>"><?= UI::icon('copy','!sp-w-3 !sp-h-3') ?>Copiar enlace</button></div><div class="!sp-flex !sp-flex-wrap !sp-justify-end !sp-gap-2 !sp-mt-2"><?php foreach(Workspace::documents($row) as $key=>$document): ?><button type="button" class="!sp-px-2 !sp-py-1 !sp-rounded !sp-border !sp-border-solid <?= $key==='agua'?'!sp-border-cyan-200 !sp-bg-cyan-50 !sp-text-cyan-800':($key==='gas'?'!sp-border-rose-200 !sp-bg-rose-50 !sp-text-rose-700':'!sp-border-amber-200 !sp-bg-amber-50 !sp-text-amber-900') ?> !sp-text-[9px] !sp-cursor-pointer" data-scm-open-iframe data-iframe-url="<?= $e($document['url']) ?>" data-iframe-title="<?= $e($document['title']) ?>"><?= $e($document['title']) ?></button><?php endforeach ?></div></td></tr>
<?php endforeach ?>
<?php if(!$rows): ?><tr><td colspan="6" class="!sp-p-8 !sp-text-center !sp-text-service-muted">No hay revisiones con estos filtros.</td></tr><?php endif ?></tbody></table></div>
<footer class="!sp-p-4 !sp-bg-slate-50/50 !sp-flex !sp-flex-wrap !sp-justify-between !sp-items-center !sp-gap-3 !sp-text-[10px] !sp-text-service-muted"><span>Mostrando <?= $total?($page-1)*30+1:0 ?> a <?= min($page*30,$total) ?> de <?= $total ?> revisiones</span><div class="!sp-flex !sp-items-center !sp-gap-2"><button type="button" class="<?= UI::SECONDARY ?>" data-services-history-page="<?= $page-1 ?>" <?= $page<=1?'disabled':'' ?>>Anterior</button><span class="!sp-bg-service-navy !sp-text-white !sp-px-3 !sp-py-2 !sp-rounded"><?= $page ?></span><button type="button" class="<?= UI::SECONDARY ?>" data-services-history-page="<?= $page+1 ?>" <?= $page>=$pages?'disabled':'' ?>>Siguiente</button></div></footer></div></div>
