<?php
use SCM\Modules\Pending\PublicServicesUi as UI;
$e = [SCM\Modules\Pending\PublicServicesDocument::class, 'e'];
$dueThisMonth=0; $now=new DateTimeImmutable('now',new DateTimeZone('America/Bogota'));
foreach($items as $item) if(!empty($item['due']) && date('Y-m',(int)$item['due'])===$now->format('Y-m')) $dueThisMonth++;
$cards=[['Contratos pendientes',$count,'Revisión calculada','Total de contratos con ciclo activo','document','rsp-kpi-count2','!sp-text-service-navy'],['Sin configurar',count($configurationItems),'Atención requerida','No contabilizados en pendientes','alert','','!sp-text-amber-600'],['Corte operativo',$corte,'Vigencia activa','Periodo fiscal y contractual base','calendar','rsp-kpi-corte','!sp-text-service-navy'],['Vencen este mes',$dueThisMonth,'Prioridad alta',$now->format('m/Y').' en curso','calendar','','!sp-text-rose-600']];
foreach($cards as $i=>$card): ?>
<div class="<?= str_replace('!sp-border-slate-200', $i===1 ? '!sp-border-service-yellow' : '!sp-border-slate-200', UI::CARD) ?> !sp-p-4 <?= $i===1?'!sp-border-service-yellow !sp-bg-amber-50/30':'' ?>"><div class="!sp-flex !sp-justify-between !sp-items-center"><span class="!sp-text-[10px] !sp-uppercase !sp-font-semibold <?= $card[6] ?>"><?= $e($card[0]) ?></span><span class="!sp-p-2 !sp-rounded-lg <?= $i===1?'!sp-bg-amber-100':'!sp-bg-slate-50' ?>"><?= UI::icon($card[4]) ?></span></div><div class="!sp-flex !sp-flex-wrap !sp-items-center !sp-gap-2 !sp-mt-2"><strong <?= $card[5]?'id="'.$card[5].'"':'' ?> class="!sp-text-2xl !sp-font-extrabold <?= $card[6] ?>"><?= $e($card[1]) ?></strong><span class="!sp-text-[9px] !sp-rounded !sp-border !sp-border-solid !sp-border-slate-200 !sp-px-1.5 !sp-py-0.5 <?= $card[6] ?>"><?= $e($card[2]) ?></span></div><p class="!sp-m-0 !sp-mt-1 !sp-text-[10px] !sp-text-service-muted"><?= $e($card[3]) ?></p></div>
<?php endforeach ?>
