<?php
use SCM\Modules\Pending\PublicServicesUi as UI;
use SCM\Modules\Pending\PublicServicesSchedule;
$e=[SCM\Modules\Pending\PublicServicesDocument::class,'e'];
$contract=(array)($context['contract']??[]);$services=(array)($context['services']??[]);$employee=(array)($context['employee']??[]);
$id=(string)($contract['_ID']??'');$code=(string)($contract['contrato']??$id);
$next=(new DateTimeImmutable('@'.PublicServicesSchedule::next(time())))->setTimezone(new DateTimeZone('America/Bogota'));
$months=[1=>'Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
$nextMonth=$months[(int)$next->format('n')];
?>
<form class="scm-public-services-review-form !sp-font-sans !sp-text-service-navy !sp-p-0 !sp-block" data-public-services-review-form autocomplete="off" novalidate>
<input type="hidden" name="contract_id" value="<?= $e($id) ?>"><input type="hidden" name="configuration_present" value="1"><input type="hidden" name="request_token" value="<?= $e($context['request_token']??'') ?>">
<div class="!sp-p-5 sm:!sp-p-6 !sp-space-y-4">
<div class="!sp-grid !sp-grid-cols-2 lg:!sp-grid-cols-4 !sp-gap-3">
<?php foreach([['Contrato','#'.$code,'document'],['Inmueble SIMI','#'.($contract['inmueble']??'-'),'building'],['Fecha revisión',$context['review_date']??date('Y-m-d'),'calendar'],['Funcionario',$employee['nombre']??'','user']] as $i=>$meta): ?>
<div class="!sp-bg-service-lilac !sp-rounded-xl !sp-p-3 !sp-flex !sp-gap-3 !sp-items-center"><span class="!sp-bg-white !sp-p-2 !sp-rounded-lg <?= $i===3?'!sp-text-amber-700':'!sp-text-service-blue' ?>"><?= UI::icon($meta[2],'!sp-w-5 !sp-h-5') ?></span><div class="!sp-min-w-0"><span class="!sp-block !sp-text-[9px] !sp-uppercase !sp-tracking-wide"><?= $meta[0] ?></span><strong class="!sp-block !sp-text-xs !sp-leading-tight"><?= $e($meta[1]) ?></strong><?php if($i===3): ?><small class="!sp-text-[9px] !sp-text-service-muted">ID empleado: <?= $e($employee['id_empleado']??'') ?></small><?php endif ?></div></div>
<?php endforeach ?></div>
<div class="!sp-bg-service-lilac !sp-rounded-xl !sp-p-4 !sp-flex !sp-gap-3 !sp-items-start"><?= UI::icon('building','!sp-w-5 !sp-h-5 !sp-text-service-blue') ?><div><span class="!sp-block !sp-text-[9px] !sp-uppercase">Dirección del inmueble</span><strong class="!sp-block !sp-text-xs"><?= $e($contract['direccion']??'-') ?></strong><small class="!sp-block !sp-text-[10px] !sp-mt-1">Arrendatario: <?= $e($contract['arrendatario']??'-') ?></small></div></div>
<fieldset class="!sp-border-0 !sp-p-0 !sp-m-0 !sp-min-w-0"><legend class="!sp-font-bold !sp-text-sm !sp-mb-2">Servicios del contrato</legend><p class="!sp-m-0 !sp-mb-4 !sp-text-[10px] !sp-leading-relaxed !sp-text-service-muted">Activa los servicios que realmente tiene el inmueble y corrige sus identificadores o medidores. Desmarcar «Revisar ahora» conserva el servicio y no genera su acta. Desactivar el servicio lo retira de la configuración sin eliminar su trazabilidad histórica.</p>
<?php foreach($services as $key=>$service): $configured=!empty($service['configured']);$panelId='scm-public-service-fields-'.$key; ?>
<section class="scm-public-service-card !sp-border-0 !sp-shadow-none !sp-rounded-xl !sp-overflow-hidden !sp-mb-4 <?= $configured?'is-selected':'' ?>" data-public-service-card="<?= $e($key) ?>">
<div class="!sp-bg-service-lilac/70 !sp-p-3 !sp-flex !sp-flex-wrap !sp-justify-between !sp-gap-3 !sp-items-center">
<label class="!sp-flex !sp-gap-2 !sp-items-center !sp-cursor-pointer"><input class="!sp-accent-service-yellow !sp-w-4 !sp-h-4" type="checkbox" name="servicios_configurados[]" value="<?= $e($key) ?>" <?= $configured?'checked':'' ?> aria-controls="<?= $e($panelId) ?>" aria-expanded="<?= $configured?'true':'false' ?>"><span class="!sp-p-1 !sp-rounded !sp-bg-amber-100"><?= UI::icon($key==='agua'?'drop':'bolt') ?></span><span><strong class="!sp-block !sp-text-xs"><?= $e($service['display_label']??$service['label']??$key) ?></strong><small class="!sp-block !sp-text-[9px] !sp-text-service-muted">El inmueble tiene este servicio</small></span></label>
<label class="!sp-inline-flex !sp-gap-2 !sp-items-center !sp-bg-white !sp-border !sp-border-solid !sp-border-slate-200 !sp-rounded-lg !sp-p-2 !sp-text-[10px] !sp-cursor-pointer"><input class="!sp-accent-service-navy" type="checkbox" name="servicios[]" value="<?= $e($key) ?>" <?= $configured?'checked':'' ?>><strong>Revisar ahora</strong><small>Generar su acta</small></label></div>
<div class="scm-public-service-fields !sp-grid !sp-grid-cols-1 sm:!sp-grid-cols-2 lg:!sp-grid-cols-4 !sp-gap-3 !sp-p-3" id="<?= $e($panelId) ?>">
<?php foreach([['account','account_field',$service['account_label']??'Cuenta','data-public-service-account'],['meter','meter_field','Número de medidor','data-public-service-meter']] as $field): ?><label><span class="<?= UI::LABEL ?>"><?= $e($field[2]) ?> <b class="!sp-text-rose-500" data-public-service-required>*</b></span><input class="<?= UI::field('!sp-bg-service-lilac') ?> !sp-border-0" name="<?= $e($service[$field[1]]??'') ?>" value="<?= $e($service[$field[0]]??'') ?>" maxlength="180" <?= $field[3] ?>></label><?php endforeach ?>
<label data-public-service-review-only><span class="<?= UI::LABEL ?>">Resultado en tiempo <b class="!sp-text-rose-500">*</b></span><select class="<?= UI::field('!sp-bg-service-lilac') ?> !sp-border-0" name="<?= $e($service['status_field']??'') ?>" required data-public-service-status><option value="">Selecciona un resultado</option><option value="Al dia">Al día / sin mora</option><option value="30 dias">30 días</option><option value="60 dias">60 días</option><option value="Estado critico">Estado crítico / superior a 90 días</option></select></label>
<label data-public-service-review-only><span class="<?= UI::LABEL ?>">Valor reportado (COP) <b class="!sp-text-rose-500">*</b></span><input class="<?= UI::field('!sp-bg-service-lilac') ?> !sp-border-0" name="<?= $e($service['amount_field']??'') ?>" value="0" inputmode="numeric" pattern="[0-9.$, ]+" required data-public-service-amount><small class="!sp-block !sp-text-[9px] !sp-text-service-muted !sp-mt-1">Usa 0 si el servicio está al día.</small></label>
</div></section><?php endforeach ?></fieldset>
<aside class="!sp-bg-amber-50 !sp-rounded-lg !sp-border-l-4 !sp-border-y-0 !sp-border-r-0 !sp-border-solid !sp-border-amber-700 !sp-p-4 !sp-text-[10px] !sp-leading-relaxed"><strong class="!sp-block !sp-mb-1">Al guardar</strong><span data-public-services-review-notice data-review-text="Se actualizarán siempre los servicios y sus datos. Además, se creará la revisión, se generarán las actas marcadas y se encolarán los correos. El próximo mes será <?= $e($nextMonth) ?>." data-config-text="Se actualizarán los servicios y sus datos, con historial del funcionario. Como no hay servicios marcados para revisar, no se crearán actas ni correos y no cambiará el próximo mes.">Se actualizarán siempre los servicios y sus datos. Además, se creará la revisión, se generarán las actas marcadas y se encolarán los correos. El próximo mes será <?= $e($nextMonth) ?>.</span></aside>
<div class="scm-public-services-review-error !sp-text-rose-700 !sp-bg-rose-50 !sp-p-3 !sp-rounded-lg !sp-text-xs" role="alert" aria-live="assertive" hidden></div>
</div><footer class="!sp-sticky !sp-bottom-0 !sp-z-10 !sp-bg-service-lilac !sp-p-4 !sp-flex !sp-flex-wrap !sp-justify-end !sp-gap-3"><button type="button" class="<?= UI::SECONDARY ?>" data-public-services-review-close>Cancelar</button><button type="submit" class="<?= UI::PRIMARY ?>" data-public-services-review-submit>Guardar servicios, revisión y actas</button></footer></form>
