<?php
use SCM\Modules\Pending\PublicServicesUi as UI;
$e=[SCM\Modules\Pending\PublicServicesDocument::class,'e'];
$groups=[['items'=>$configurationItems,'configuration'=>true],['items'=>$items,'configuration'=>false]];
foreach($groups as $group): $configuration=$group['configuration']; $rows=$group['items']; $canSchedule=!$configuration && !empty($rows[0]['can_adjust_schedule']); if($configuration&&!$rows)continue; ?>
<<?= $configuration?'details':'div' ?> class="<?= str_replace(['!sp-border-slate-200','!sp-bg-white'], [$configuration ? '!sp-border-service-yellow' : '!sp-border-slate-200', $configuration ? '!sp-bg-amber-50/50' : '!sp-bg-white'], UI::CARD) ?> !sp-mb-5 <?= $configuration?'!sp-border-service-yellow !sp-bg-amber-50/50 !sp-p-4':'' ?>" data-services-list="<?= $configuration?'configuration':'pending' ?>">
<?php if($configuration): ?><summary class="!sp-cursor-pointer !sp-font-bold !sp-text-sm !sp-text-amber-900"><span class="!sp-inline-flex !sp-align-middle !sp-p-2 !sp-mr-2 !sp-bg-amber-500 !sp-text-white !sp-rounded-lg"><?= UI::icon('alert') ?></span>Sin servicios configurados / por verificar <span class="!sp-text-[10px] !sp-bg-amber-900 !sp-text-white !sp-rounded !sp-px-2 !sp-py-1"><?= count($rows) ?> contratos</span></summary><p class="!sp-text-xs !sp-text-service-muted !sp-mt-2 !sp-mb-4">Estos contratos no cuentan como revisiones pendientes. Puedes completar o corregir sus servicios. Este grupo no depende del filtro de mes.</p>
<?php else: ?><div class="!sp-p-4 !sp-flex !sp-flex-wrap !sp-items-center !sp-justify-between !sp-gap-3"><div><h3 class="!sp-m-0 !sp-font-bold !sp-text-sm">Listado de contratos con revisión pendiente <span class="!sp-bg-service-navy !sp-text-service-yellow !sp-text-[9px] !sp-px-2 !sp-py-1 !sp-rounded"><?= count($rows) ?> registros</span></h3><p class="!sp-m-0 !sp-mt-1 !sp-text-[10px] !sp-text-service-muted">Ordenados cronológicamente por fecha límite de siguiente revisión.</p></div><label class="!sp-flex !sp-items-center !sp-gap-2 !sp-text-xs">Mostrar: <select class="<?= UI::INPUT ?> !sp-w-28" data-services-page-size><option>10</option><option>25</option><option>50</option><option value="all">Todos</option></select></label></div><?php endif ?>
<?php if($canSchedule): ?><?= UI::render('bulk-schedule',[]) ?><?php endif ?>
<div class="!sp-overflow-x-auto"><table class="!sp-w-full !sp-border-collapse !sp-text-[10px] !sp-text-service-navy !sp-min-w-[1250px]" data-services-contract-table><thead class="<?= $configuration?'!sp-bg-amber-100/50':'!sp-bg-slate-50' ?>"><tr><?php foreach(['Contrato','Inmueble','Dirección del inmueble','Propietario','Arrendatario','Inicio','Fin','Entrega','Últ. revisión','Sig. revisión','Acciones'] as $label): ?><th class="!sp-text-left !sp-text-[9px] !sp-uppercase !sp-tracking-wide !sp-font-bold !sp-px-3 !sp-py-4 !sp-border-x-0 !sp-border-y !sp-border-solid !sp-border-slate-200"><?php if($canSchedule && $label==='Contrato'): ?><input type="checkbox" class="!sp-mr-2 !sp-accent-service-navy" data-services-select-page aria-label="Seleccionar contratos de esta página"><?php endif ?><?= $label ?></th><?php endforeach ?></tr></thead><tbody>
<?php foreach($rows as $item): $row=(array)($item['row']??[]); $pk=(string)($row['_ID']??'');$code=(string)($row['contrato']??$pk);$needs=!empty($item['needs_service_configuration']); ?>
<tr data-services-contract-row data-services-due="<?= (int)($item['due']??0) ?>" class="!sp-bg-white hover:!sp-bg-slate-50 !sp-border-b !sp-border-solid !sp-border-slate-100">
<td class="!sp-border-x-0 !sp-border-y-0 !sp-px-3 !sp-py-4"><?php if($canSchedule): ?><input type="checkbox" class="!sp-mr-2 !sp-accent-service-navy" data-services-select-contract data-contract-id="<?= $e($pk) ?>" data-contract-code="<?= $e($code) ?>" data-request-token="<?= $e($item['adjustment_token']??'') ?>" aria-label="Seleccionar contrato <?= $e($code) ?>"><?php endif ?><span class="!sp-inline-flex !sp-px-2 !sp-py-1 !sp-rounded !sp-bg-amber-50 !sp-border !sp-border-solid !sp-border-amber-200 !sp-text-amber-900 !sp-font-bold">#<?= $e($code) ?></span></td><td class="!sp-border-x-0 !sp-border-y-0 !sp-px-3 !sp-py-4"><span class="!sp-inline-flex !sp-px-2 !sp-py-1 !sp-rounded !sp-bg-emerald-50 !sp-border !sp-border-solid !sp-border-emerald-200 !sp-text-emerald-700 !sp-font-semibold"><?= $e($row['inmueble']??'-') ?></span></td>
<?php foreach(['direccion','propietario','arrendatario'] as $field): ?><td class="!sp-border-x-0 !sp-border-y-0 !sp-px-3 !sp-py-4 !sp-max-w-[200px] !sp-leading-relaxed <?= $field==='direccion'?'!sp-font-medium':'' ?>"><?= $e($row[$field]??'-') ?></td><?php endforeach ?>
<?php foreach(['inicio_contrato','fin_contrato','fecha_entrega'] as $field): ?><td class="!sp-border-x-0 !sp-border-y-0 !sp-px-3 !sp-py-4 !sp-whitespace-nowrap !sp-text-service-muted"><?= $e(UI::date($row[$field]??null)) ?></td><?php endforeach ?>
<td class="!sp-border-x-0 !sp-border-y-0 !sp-px-3 !sp-py-4 !sp-whitespace-nowrap"><span class="!sp-bg-slate-100 !sp-rounded !sp-px-2 !sp-py-1"><?= $e(UI::date($item['ultima']??0)) ?></span></td><td class="!sp-border-x-0 !sp-border-y-0 !sp-px-3 !sp-py-4 !sp-text-rose-600 !sp-font-semibold"><?= $needs?'Sin configurar':$e(UI::date($item['due']??0)) ?></td>
<td class="!sp-border-x-0 !sp-border-y-0 !sp-px-3 !sp-py-4"><div class="!sp-flex !sp-items-center !sp-gap-2 !sp-whitespace-nowrap"><?php if($pk!==''&&strtolower(trim((string)($row['estado']??'')))!=='recibido'): ?><button type="button" class="<?= UI::SECONDARY ?> !sp-text-[10px]" data-scm-mark-contract-received data-contract-context="servicios-publicos" data-contract-id="<?= $e($pk) ?>" data-contract-code="<?= $e($code) ?>">Contrato recibido</button><?php endif ?><button type="button" class="<?= UI::NAVY ?>" data-scm-open-public-services-review data-contract-id="<?= $e($pk) ?>" data-contract-code="<?= $e($code) ?>"><?= UI::icon('edit','!sp-w-3 !sp-h-3 !sp-text-service-yellow') ?><?= $needs?'Configurar servicios':'Agregar revisión / editar servicios' ?></button></div><?php if(!empty($item['can_adjust_schedule'])): ?><?= UI::render('date-adjustment', compact('item','row','pk','code')) ?><?php if($canSchedule): ?><button type="button" class="<?= UI::SECONDARY ?> !sp-mt-2" data-services-schedule-one><?= UI::icon('calendar') ?>Programar para otro mes</button><?php endif ?><?php endif ?></td></tr>
<?php endforeach ?>
<?php if(!$rows): ?><tr><td colspan="11" class="!sp-p-8 !sp-text-center !sp-text-service-muted">No hay contratos pendientes con los filtros actuales.</td></tr><?php endif ?>
</tbody></table></div>
<?php if(!$configuration): ?><footer class="!sp-flex !sp-flex-wrap !sp-justify-between !sp-items-center !sp-gap-3 !sp-bg-slate-50/50 !sp-p-4 !sp-text-[10px] !sp-text-service-muted"><span data-services-page-summary></span><div class="!sp-flex !sp-gap-1 !sp-items-center"><button type="button" class="<?= UI::SECONDARY ?>" data-services-page-step="-1">Anterior</button><span data-services-page-number class="!sp-bg-service-yellow !sp-rounded !sp-px-3 !sp-py-2">1</span><button type="button" class="<?= UI::SECONDARY ?>" data-services-page-step="1">Siguiente</button></div></footer><?php endif ?>
</<?= $configuration?'details':'div' ?>>
<?php endforeach ?>
