<?php

namespace SCM\Support\TimelineMaps;

final class PreventivaTimelineMap
{
  /**
   * @return array<int,array<string,mixed>>
   */
  public static function steps(): array
  {
    return [
      [
        'key' => 'tarea_generada',
        'label' => 'Tarea generada',
        'icon' => 'Q',
        'table' => 'wp_jet_cct_tickets',
        'date_columns' => ['cct_created'],
        'ts_fields' => ['ticket_cct_created', 'cct_created', 'fecha'],
        'done_if' => 'always',
        'empty_text' => 'Sin fecha de queja',
      ],
      [
        'key' => 'cita_agendada',
        'label' => 'Cita agendada',
        'icon' => '02',
        'table' => 'calendario_actividades',
        'date_columns' => ['fecha_inicio'],
        'ts_field' => 'cita_fecha_inicio',
        'done_if' => 'field_not_empty',
        'done_field' => 'cita_fecha_inicio',
        'elapsed_from_fields' => ['ticket_cct_created'],
        'elapsed_from_label' => 'Tarea generada',
        'link_url' => 'https://calendar-skc.netlify.app/evento/{id_cita_agendada}',
        'empty_text' => 'Cita sin agendar',
      ],
      [
        'key' => 'revision_preventiva_registrada',
        'label' => 'Revision preventiva registrada',
        'icon' => 'R',
        'table' => 'wp_jet_cct_revision_preventiva',
        'date_columns' => ['cct_created', 'fecha_revision_preventiva', 'fecha'],
        'ts_field' => 'prev_fecha_registro',
        'done_if' => 'field_not_empty',
        'done_field' => 'prev_fecha_registro',
        'elapsed_from_fields' => ['cita_fecha_inicio', 'ticket_cct_created'],
        'elapsed_from_label' => 'Cita agendada',
        'link_url' => 'https://sucasainmobiliaria.com.co/revision-preventiva/?numero={id_revision_preventiva}',
        'empty_text' => 'Sin revision preventiva',
      ],
      [
        'key' => 'revision_preventiva_enviada',
        'label' => 'Preventiva enviada',
        'icon' => 'R',
        'table' => 'wp_jet_cct_revision_preventiva',
        'date_columns' => ['fecha_envio'],
        'ts_field' => 'prev_fecha_envio',
        'done_if' => 'field_in',
        'done_field' => 'prev_se_envio',
        'done_values' => ['Si', 'SI', 'si'],
        'elapsed_from_fields' => ['prev_fecha_registro'],
        'elapsed_from_label' => 'Revision preventiva registrada',
        'link_url' => 'https://sucasainmobiliaria.com.co/revision-preventiva/?numero={id_revision_preventiva}',
        'empty_text' => 'Sin envio de preventiva',
      ],
      [
        'key' => 'cotizacion_registrada',
        'label' => 'Cotizacion registrada',
        'icon' => 'C',
        'table' => 'wp_jet_cct_cotizacion_mantenimiento',
        'date_columns' => ['cct_created', 'created_at', 'fecha', 'fecha_actualizacion', 'cct_modified', 'updated_at'],
        'ts_field' => 'cot_fecha_registro',
        'done_if' => 'field_not_empty',
        'done_field' => 'cot_fecha_registro',
        'show_if' => 'field_in',
        'show_field' => 'prev_encontro_danos',
        'show_values' => ['Si', 'SI', 'si'],
        'elapsed_from_fields' => ['prev_fecha_registro'],
        'elapsed_from_label' => 'Revision preventiva registrada',
        'link_url' => 'https://sucasainmobiliaria.com.co/cotizacion-de-mantenimiento/?numero={id_cotizacion_mantenimiento}',
        'empty_text' => 'Sin cotizacion registrada',
      ],
      [
        'key' => 'cotizacion_enviada',
        'label' => 'Cotizacion enviada',
        'icon' => '06',
        'table' => 'wp_jet_cct_cotizacion_mantenimiento',
        'date_columns' => ['fecha_envio_cotizacion_mantenimiento', 'fecha_envio', 'fecha_enviada', 'fecha_envio_correo'],
        'ts_field' => 'cot_fecha_envio',
        'done_if' => 'field_not_empty',
        'done_field' => 'cot_fecha_envio',
        'show_if' => 'field_in',
        'show_field' => 'prev_encontro_danos',
        'show_values' => ['Si', 'SI', 'si'],
        'elapsed_from_fields' => ['cot_fecha_registro'],
        'elapsed_from_label' => 'Cotizacion registrada',
        'link_url' => 'https://sucasainmobiliaria.com.co/cotizacion-de-mantenimiento/?numero={id_cotizacion_mantenimiento}',
        'empty_text' => 'Sin envio de cotizacion',
      ],
      [
        'key' => 'respuesta_cotizacion',
        'label' => 'Respuesta cotizacion',
        'icon' => '07',
        'table' => 'wp_jet_cct_cotizacion_mantenimiento',
        'date_columns' => ['fecha_respuesta', 'fecha_actualizacion', 'cct_modified', 'updated_at'],
        'ts_field' => 'cot_fecha_respuesta',
        'done_if' => 'field_not_empty',
        'done_field' => 'cot_fecha_respuesta',
        'show_if' => 'field_in',
        'show_field' => 'prev_encontro_danos',
        'show_values' => ['Si', 'SI', 'si'],
        'elapsed_from_fields' => ['cot_fecha_envio'],
        'elapsed_from_label' => 'Cotizacion enviada',
        'link_url' => 'https://sucasainmobiliaria.com.co/cotizacion-de-mantenimiento/?numero={id_cotizacion_mantenimiento}',
        'empty_text' => 'Sin respuesta de cotizacion',
      ],
      [
        'key' => 'trabajo_finalizado',
        'label' => 'Trabajo finalizado',
        'icon' => '08',
        'table' => 'wp_jet_cct_actas_de_satisfaccion',
        'date_columns' => ['cct_created'],
        'ts_field' => 'acta_fecha_creada',
        'done_if' => 'field_not_empty',
        'done_field' => 'acta_fecha_creada',
        'show_if' => 'field_in',
        'show_field' => 'cot_estado',
        'show_values' => ['Aprobada', 'APROBADA', 'aprobada'],
        'elapsed_from_fields' => ['cot_fecha_respuesta'],
        'elapsed_from_label' => 'Respuesta cotizacion',
        'link_url' => 'https://sucasainmobiliaria.com.co/acta-de-satisfaccion/?numero={id_acta_satisfaccion}',
        'empty_text' => 'Sin fecha de trabajo finalizado',
      ],
    ];
  }
}
